apiVersion: multitenancy.600lyy.io/v1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: tenant
    app.kubernetes.io/instance: tenant-sample
    app.kubernetes.io/part-of: sample-tenant-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: sample-tenant-operator
  name: tenant-sample
spec:
  # TODO(user): Add fields here
  adminEmail: admin123@600lyy.com
  adminGroups:
    - tenant-sample-admins
  userGroups:
    - tenant-sample-users
    - another-group-users
  namespaces:
    - tenant-sample-ns1
    - tenant-sample-ns2